"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Bot, ChevronRight, Database, Filter, RotateCcw, Send, ShieldCheck, X } from "lucide-react";
import { AuthStatus } from "./auth-status";
import { API } from "../lib/config";

type Spend = { invoice_id: string; supplier: string; category: string; location: string; division: string; amount: number; currency: string; source: string; managed: boolean; contract_id: string | null; po_id: string | null; invoice_date: string; quality_flags: string[] };
const all = "All";

export default function Dashboard() {
  const [records, setRecords] = useState<Spend[]>([]);
  const [category, setCategory] = useState(all), [supplier, setSupplier] = useState(all), [location, setLocation] = useState(all), [source, setSource] = useState(all), [coverage, setCoverage] = useState(all);
  const [selected, setSelected] = useState<Spend | null>(null), [question, setQuestion] = useState(""), [answer, setAnswer] = useState("Ask about unmanaged spend, suppliers, or quality issues."), [loading, setLoading] = useState(true), [asking, setAsking] = useState(false);
  useEffect(() => { fetch(`${API}/api/spend`).then((response) => response.json()).then(setRecords).finally(() => setLoading(false)); }, []);
  const options = useMemo(() => ({ categories: [all, ...Array.from(new Set(records.map((record) => record.category)))], suppliers: [all, ...Array.from(new Set(records.map((record) => record.supplier)))], locations: [all, ...Array.from(new Set(records.map((record) => record.location)))], sources: [all, ...Array.from(new Set(records.map((record) => record.source)))] }), [records]);
  const filtered = records.filter((record) => (category === all || record.category === category) && (supplier === all || record.supplier === supplier) && (location === all || record.location === location) && (source === all || record.source === source) && (coverage === all || (coverage === "Managed" ? record.managed : !record.managed)));
  const total = filtered.reduce((sum, record) => sum + record.amount, 0), managedTotal = filtered.filter((record) => record.managed).reduce((sum, record) => sum + record.amount, 0), activeFilters = [category, supplier, location, source, coverage].filter((value) => value !== all).length;
  function resetFilters() { setCategory(all); setSupplier(all); setLocation(all); setSource(all); setCoverage(all); }
  async function askAgent(event: React.FormEvent) { event.preventDefault(); if (!question.trim()) return; setAsking(true); try { const response = await fetch(`${API}/api/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: question }) }); setAnswer((await response.json()).response); } finally { setAsking(false); } }
  return <main>
    <header><div className="brand"><span className="mark">SV</span><span>Spend visibility</span></div><span className="status"><ShieldCheck size={16} /> Connected to local data plane</span><AuthStatus /></header>
    <section className="intro"><div><p className="eyebrow">GNFR intelligence / live workspace</p><h1>See the spend<br /><em>behind the signal.</em></h1><p className="lede">A unified view across Oracle AP, Coupa, and EAA, with source provenance and data quality in plain sight.</p></div><div className="refresh">Last refreshed from synthetic source</div></section>
    <section className="metrics"><div><span>Filtered spend</span><strong>${total.toLocaleString()}</strong><small><ArrowUpRight size={14} /> {filtered.length} matching records</small></div><div><span>Managed coverage</span><strong>{total ? Math.round(managedTotal / total * 100) : 0}%</strong><small>Across active contracts</small></div><div><span>Source records</span><strong>{filtered.length}</strong><small><Database size={14} /> {activeFilters ? `${activeFilters} filters active` : "Full population"}</small></div></section>
    <section className="workspace"><div className="data-panel"><div className="section-head"><div><p className="eyebrow">Spend population</p><h2>Transactions</h2></div><button className="reset" onClick={resetFilters}><RotateCcw size={14} /> Reset filters</button></div><div className="filter-bar"><Filter size={15} /><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Category filter">{options.categories.map((item) => <option key={item}>{item}</option>)}</select><select value={supplier} onChange={(event) => setSupplier(event.target.value)} aria-label="Supplier filter">{options.suppliers.map((item) => <option key={item}>{item}</option>)}</select><select value={location} onChange={(event) => setLocation(event.target.value)} aria-label="Location filter">{options.locations.map((item) => <option key={item}>{item}</option>)}</select><select value={source} onChange={(event) => setSource(event.target.value)} aria-label="Source filter">{options.sources.map((item) => <option key={item}>{item}</option>)}</select><select value={coverage} onChange={(event) => setCoverage(event.target.value)} aria-label="Coverage filter"><option>All</option><option>Managed</option><option>Unmanaged</option></select></div><div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Category</th><th>Location</th><th>Source</th><th>Coverage</th><th className="amount">Amount</th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan={7}>Loading spend population...</td></tr> : filtered.map((record) => <tr key={record.invoice_id} className={selected?.invoice_id === record.invoice_id ? "selected-row" : ""} onClick={() => setSelected(record)}><td><b>{record.supplier}</b><small>{record.invoice_id}</small></td><td>{record.category}</td><td>{record.location}</td><td><span className="source">{record.source}</span></td><td><span className={record.managed ? "pill managed" : "pill unmanaged"}>{record.managed ? "Managed" : "Unmanaged"}</span>{record.quality_flags.length > 0 && <small className="flag">Needs review</small>}</td><td className="amount">${record.amount.toLocaleString()}</td><td><ChevronRight size={15} /></td></tr>)}</tbody></table></div></div>
      <aside className="agent-panel"><div className="agent-title"><span className="agent-icon"><Bot size={19} /></span><div><p className="eyebrow">Spend agent</p><h2>Ask the data</h2></div><span className="live-dot" /></div><p className="agent-copy">Explore the filtered population or find the next sourcing signal.</p><div className="answer">{answer}</div><form onSubmit={askAgent}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="e.g. Where is unmanaged spend?" aria-label="Ask spend agent" /><button aria-label="Send question" disabled={asking}><Send size={16} /></button></form><div className="suggestions"><button onClick={() => setQuestion("Show me the biggest unmanaged opportunity")}>Biggest opportunity</button><button onClick={() => setQuestion("Which records need review?")}>Quality issues</button></div></aside></section>
    {selected && <div className="detail-drawer"><button className="close" onClick={() => setSelected(null)} aria-label="Close detail"><X size={18} /></button><p className="eyebrow">Record detail / {selected.invoice_id}</p><h2>{selected.supplier}</h2><strong>${selected.amount.toLocaleString()}</strong><dl><dt>Category</dt><dd>{selected.category}</dd><dt>Location</dt><dd>{selected.location} / {selected.division}</dd><dt>Source</dt><dd>{selected.source}</dd><dt>PO</dt><dd>{selected.po_id ?? "Missing"}</dd><dt>Contract</dt><dd>{selected.contract_id ?? "Unmanaged"}</dd></dl>{selected.quality_flags.length > 0 && <p className="drawer-flag">{selected.quality_flags.join(" / ")}</p>}</div>}
  </main>;
}
