#!/usr/bin/env python3
"""Assemble a clean root ``.env.example`` from the plan's env variables.

Plan-phase deterministic step. Assembles the checked-in ``.env.example`` catalog
at the project root from two sources:

1. Every feature contract in ``.aah/plan/features/`` — the union of their
   ``required_env`` NAMES (parsed from each feature's ``## Required Env
   Variables`` section). These are emitted as empty ``NAME=`` placeholders for
   the user to fill.
2. ``.aah/architecture/cloud-readiness.yaml`` — the cloud resources ``/aah-access``
   already probed. Their non-secret coordinates (bucket names, ARNs, endpoints,
   regions, secret-manager reference paths) plus the AWS named profile are
   emitted **pre-filled with their real values**, so the user does NOT re-enter
   what ``/aah-access`` already captured.

This is the same catalog the build-phase startup checker enforces
(``ERR_CDR_78_EX_CONFIG``) and that build Module 0 keeps seeded. Generating it at
the end of plan lets the user create ``.env`` up front — so when build runs, the
required-env test gate already has values to read instead of blocking.

Values written here are ALWAYS non-secret: cloud coordinates and reference paths
(ARNs / secret-manager paths, never the secret plaintext) and a local profile
name. Real secrets live solely in the gitignored root ``.env``, which the user
fills after ``cp .env.example .env``.
"""

import argparse
import json
import sys
from pathlib import Path

from aah.core.common.feature_utils import load_features_from_dir


# Header contract mirrors scaffold.project.ENV_EXAMPLE_TEMPLATE so the plan-derived
# catalog reads identically to the one build Module 0 maintains.
ENV_EXAMPLE_HEADER = """\
# ─────────────────────────────────────────────────────────────────────────────
# {project_name} — environment variable catalog
#
# THIS FILE IS COMMITTED. Cloud coordinates already captured by /aah-access are
# pre-filled below (bucket names, ARNs, endpoints, regions, secret-manager
# reference paths, the AWS profile) — all NON-SECRET. Real secrets are NEVER
# written here; empty `NAME=` entries are yours to fill in .env.
#
#   cp .env.example .env    # then fill the empty values in .env
#
# .env is gitignored and is the ONLY place real secret values live.
#
# CONTRACT (enforced at app startup by the env checker):
#   * Every variable the code reads MUST be listed here.
#   * A variable that is missing or empty at startup fails the app with
#     ERR_CDR_78_EX_CONFIG naming exactly what is absent.
#
# Generated by the AAH plan phase from the planned features'
# `## Required Env Variables` sections and cloud-readiness.yaml. Build Module 0
# keeps it in sync as modules land.
# ─────────────────────────────────────────────────────────────────────────────
"""


def collect_required_env(features_dir: Path) -> list[str]:
    """Return the sorted, de-duplicated union of every feature's ``required_env``.

    Names only; malformed / non-list declarations are ignored (the plan contract
    gate already validates feature shape upstream).
    """
    keys: set[str] = set()
    for feature in load_features_from_dir(features_dir):
        raw = feature.get("required_env")
        if not isinstance(raw, list):
            continue
        for name in raw:
            if isinstance(name, str) and name.strip():
                keys.add(name.strip())
    return sorted(keys)


def collect_cloud_env(aah_path: Path) -> dict[str, str]:
    """Return pre-fillable NAME→value pairs derived from ``cloud-readiness.yaml``.

    Merges the per-service coordinate / reference vars
    (``render_runtime_env_vars``) with the cross-cutting cloud auth context
    (``render_cloud_auth_env`` — AWS profile + region). Empty when no
    cloud-readiness artifact exists. Every value is non-secret.
    """
    from aah.core.common.readiness import (
        load_runtime_resources,
        render_cloud_auth_env,
        render_runtime_env_vars,
    )

    env: dict[str, str] = {}
    resources = load_runtime_resources(aah_path)
    if isinstance(resources, dict):
        for name, value in render_runtime_env_vars(resources).items():
            if name and value != "":
                env[name] = value
    # Auth context (AWS_PROFILE / region) — additive, wins nothing already set.
    for name, value in render_cloud_auth_env(aah_path).items():
        env.setdefault(name, value)
    return env


def render_env_example(
    project_name: str, feature_keys: list[str], cloud_env: dict[str, str]
) -> str:
    """Render the full ``.env.example`` body.

    Cloud-readiness vars are written first, pre-filled with their real
    (non-secret) values. Feature-declared names not covered by a cloud value are
    written last as empty ``NAME=`` placeholders for the user to fill.
    """
    body = ENV_EXAMPLE_HEADER.format(project_name=project_name)
    body += "\n"

    if cloud_env:
        body += "# ── Cloud resources & auth (captured by /aah-access — do NOT re-enter) ────────\n"
        body += "# Non-secret coordinates from cloud-readiness.yaml. `cp .env.example .env` keeps\n"
        body += "# these values; the app authenticates with AWS_PROFILE against your ~/.aws.\n"
        for key in sorted(cloud_env):
            body += f"{key}={cloud_env[key]}\n"
        body += "\n"

    pending = [k for k in feature_keys if k not in cloud_env]
    if pending:
        body += "# ── Required by planned features (fill these in .env) ─────────────────────────\n"
        body += "# Empty values fail at startup — put real values in .env after copying.\n"
        for key in pending:
            body += f"{key}=\n"
    elif not cloud_env:
        body += "# No environment variables are declared by any planned feature yet.\n"
        body += "# Modules add their names here (and to the startup checker) as they land.\n"
    return body


def write_env_example(
    project_path: Path, features_dir: Path
) -> tuple[Path, list[str], dict[str, str], bool]:
    """Write the clean root ``.env.example``.

    Returns ``(path, feature_keys, cloud_env, existed_before)``.
    """
    project_name = project_path.name
    try:
        from aah.core.common.io_utils import read_yaml
        from aah.core.common.manifest import _manifest_path

        manifest_file = _manifest_path(project_path)
        if manifest_file.exists():
            manifest = read_yaml(manifest_file)
            project_name = (manifest or {}).get("project_name") or project_name
    except Exception:
        # Manifest is optional here — fall back to the directory name.
        pass

    feature_keys = collect_required_env(features_dir)
    cloud_env = collect_cloud_env(project_path / ".aah")
    target = project_path / ".env.example"
    existed = target.exists()
    target.write_text(
        render_env_example(project_name, feature_keys, cloud_env), encoding="utf-8"
    )
    return target, feature_keys, cloud_env, existed


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a clean root .env.example from planned features + cloud-readiness"
    )
    parser.add_argument("--project-path", type=Path, required=True, help="Project root directory")
    parser.add_argument(
        "--features-dir",
        type=Path,
        default=None,
        help="Features directory (defaults to <project-path>/.aah/plan/features)",
    )
    args = parser.parse_args()

    project_path = args.project_path.resolve()
    features_dir = args.features_dir or (project_path / ".aah" / "plan" / "features")

    if not features_dir.is_dir():
        print(f"Error: features directory not found: {features_dir}", file=sys.stderr)
        sys.exit(1)

    target, feature_keys, cloud_env, existed = write_env_example(project_path, features_dir)

    pending = [k for k in feature_keys if k not in cloud_env]
    json.dump(
        {
            "status": "regenerated" if existed else "created",
            "path": str(target),
            "cloud_prefilled": sorted(cloud_env),
            "to_fill": pending,
            "key_count": len(set(feature_keys) | set(cloud_env)),
        },
        sys.stdout,
        indent=2,
    )
    print()
    print(
        f"{'Regenerated' if existed else 'Created'} {target} "
        f"({len(cloud_env)} cloud value(s) pre-filled, {len(pending)} to fill)",
        file=sys.stderr,
    )
    sys.exit(0)


if __name__ == "__main__":
    main()
