#!/usr/bin/env python3
"""PreToolUse(Bash) guard: BLOCK package installs that violate `.aah/dependency-policy.json`.

Issue #247, Phase 3 L5-A. The PartsPulse-iter-2 incident's first two
defects (#1 MUI v5 + icons-material v9 split, #2 react-router-dom
major version mismatch) bypassed every runtime check because the
violation happened **at install time** — by the time
``deps_consistency_check`` (npm ls / pip check) ran in verify.py, the
incompatible package was already in the lockfile and on disk.

This guard intercepts ``Bash(npm install ...)`` /
``Bash(pip install ...)`` / ``Bash(pnpm add ...)`` / ``Bash(yarn add
...)`` / ``Bash(go get ...)`` / ``Bash(cargo add ...)`` /
``Bash(mvn dependency:get ...)`` and refuses installs that violate
the project's dependency policy at
``.aah/dependency-policy.json``.

The policy file is generated by ``aah.core.plan.build_dependency_policy``
during plan-phase from (a) brownfield package manifests, or (b) the
project's stack template (e.g., ``node-react-mui5`` seeds
``{"@mui/*": "^5"}``). The user can edit the file by hand; the
generator is idempotent on re-run.

Escape hatches:
  - ``AAH_DEPENDENCY_POLICY_BYPASS=1`` env var — for legitimate
    plan-phase additions where the user has explicitly approved a
    deviation.
  - Plugin-managed projects (``manifest.execution_mode == delegated``)
    short-circuit via ``delegation_guard.exit_if_delegated()``.

Exit codes:
  0 — install allowed (no policy / not an install / matches policy)
  2 — install blocked (policy violation)

Settings.json gates this guard on ``Bash`` matcher; the guard re-checks
the command pattern internally so the security boundary does not
depend on the harness's matcher.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

from aah.core.common.io_utils import read_json


BYPASS_ENV = "AAH_DEPENDENCY_POLICY_BYPASS"


# (regex, ecosystem-key) — regex captures the package spec(s) directly.
# We use word boundaries to avoid matching strings inside paths or
# similar; we use \S+ for the package portion which intentionally
# eats version specifiers (e.g. "react@^18.2.0") so we can parse them
# downstream. Multiple packages on one line are handled by
# ``re.findall`` returning all matches.
_INSTALL_PATTERNS: list[tuple[re.Pattern, str]] = [
    (re.compile(r"\bnpm\s+(?:install|i|add)\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "npm"),
    (re.compile(r"\bpnpm\s+(?:add|install|i)\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "npm"),
    (re.compile(r"\byarn\s+(?:add|install)\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "npm"),
    (re.compile(r"\b(?:uv\s+)?pip\s+install\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "pip"),
    (re.compile(r"\buv\s+add\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "pip"),
    (re.compile(r"\bpoetry\s+add\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "pip"),
    (re.compile(r"\bgo\s+get\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "go"),
    (re.compile(r"\bcargo\s+add\s+([^\s|;&<>]+(?:\s+[^\s|;&<>-][^\s|;&<>]*)*)", re.IGNORECASE), "cargo"),
    (re.compile(r"\bmvn\s+dependency:get\s+-Dartifact=([^\s|;&<>]+)", re.IGNORECASE), "mvn"),
]


def _extract_packages(command: str) -> list[tuple[str, str]]:
    """Parse a Bash command and return [(ecosystem, package_spec), ...].

    Returns an empty list when the command isn't an install. A single
    install command may yield multiple packages (e.g.
    ``npm install react react-dom``).
    """
    out: list[tuple[str, str]] = []
    for pattern, ecosystem in _INSTALL_PATTERNS:
        m = pattern.search(command)
        if not m:
            continue
        # The whole captured group may contain multiple space-separated
        # packages; split and filter out flags (anything starting with -).
        chunk = m.group(1)
        for tok in chunk.split():
            if tok.startswith("-"):
                continue
            out.append((ecosystem, tok))
        # Stop after first match — a single Bash command rarely has
        # multiple installs from different ecosystems on one line, and
        # if it does we'd over-flag by matching all patterns.
        break
    return out


def _split_pkg_spec(ecosystem: str, spec: str) -> tuple[str, str]:
    """Split a package spec into (name, version_spec).

    Examples:
      npm:  "react"             → ("react", "")
            "react@^18.2.0"     → ("react", "^18.2.0")
            "@mui/icons@^9"     → ("@mui/icons", "^9")
      pip:  "fastapi==0.110.0"  → ("fastapi", "==0.110.0")
            "fastapi"           → ("fastapi", "")
            "fastapi[all]>=2"   → ("fastapi[all]", ">=2")
      go:   "github.com/x/y@v1.2.3" → ("github.com/x/y", "v1.2.3")
      cargo:"serde"             → ("serde", "")
            "serde@1.0"         → ("serde", "1.0")
      mvn:  "group:artifact:1.0" → ("group:artifact", "1.0")
    """
    if ecosystem in ("npm", "go", "cargo"):
        # `@` separates name from version, but npm allows scoped names
        # starting with @. Split on the LAST @ unless the only @ is the
        # leading scope marker.
        if spec.startswith("@"):
            # Scoped npm name: ignore the leading @, then look for @ in the rest.
            rest = spec[1:]
            if "@" in rest:
                name_part, _, version = rest.rpartition("@")
                return ("@" + name_part, version)
            return (spec, "")
        if "@" in spec:
            name, _, version = spec.rpartition("@")
            return (name, version)
        return (spec, "")
    if ecosystem == "pip":
        # pip uses ==, >=, <=, ~=, !=, < or >. Find the first occurrence.
        m = re.search(r"(==|>=|<=|~=|!=|<|>)", spec)
        if m:
            i = m.start()
            return (spec[:i], spec[i:])
        return (spec, "")
    if ecosystem == "mvn":
        # group:artifact:version
        parts = spec.split(":")
        if len(parts) >= 3:
            return (":".join(parts[:2]), parts[2])
        return (spec, "")
    return (spec, "")


def _glob_matches(pattern: str, name: str) -> bool:
    """Wildcard match: ``@mui/*`` matches ``@mui/icons-material``."""
    if "*" not in pattern:
        return pattern == name
    # Convert glob-style `*` to regex `.*`, anchored both ends.
    rx = "^" + re.escape(pattern).replace(r"\*", ".*") + "$"
    return re.match(rx, name) is not None


def _major_version(version: str) -> str | None:
    """Extract the major-version digits from a version spec.

    Examples:
      "^18.2.0"  → "18"
      "~5.4"     → "5"
      "5.4.2"    → "5"
      "v1.2.3"   → "1"
      "*"        → None  (no major; matches anything)
      ""         → None
    """
    if not version:
        return None
    # Strip leading ^, ~, =, v, >, <, !
    v = version.lstrip("^~=v><!")
    m = re.match(r"(\d+)", v)
    return m.group(1) if m else None


def _violates_policy(policy_version: str, requested_version: str) -> bool:
    """True iff `requested_version` violates `policy_version`.

    The policy form we support is intentionally simple — major-version
    pinning ("^N", "~N", "N.x"). Patch-level constraints aren't enforced;
    those belong in lockfiles. Substring/major check is enough to
    catch the PartsPulse class (MUI v5 + icons v9 splits).

    A request with no version (``""``) cannot be evaluated for major-version
    compatibility — we conservatively allow it. The lockfile + the
    deps_consistency_check step in verify.py will catch downstream
    incompatibilities.
    """
    pol_major = _major_version(policy_version)
    req_major = _major_version(requested_version)
    if pol_major is None:
        return False  # Policy doesn't pin a major → nothing to violate.
    if req_major is None:
        return False  # Request doesn't pin → allow; let the lockfile decide.
    return pol_major != req_major


def _load_policy(project_path: Path) -> dict | None:
    """Load .aah/dependency-policy.json. Returns None when absent or unreadable."""
    policy_path = project_path / ".aah" / "dependency-policy.json"
    if not policy_path.exists():
        return None
    try:
        data = read_json(policy_path)
    except Exception:
        return None
    if not isinstance(data, dict):
        return None
    return data


def _find_project_root() -> Path | None:
    """Walk up from CWD looking for the nearest ``.aah`` directory.

    Returns the project root, or None if no .aah ancestor exists.
    """
    cwd = Path.cwd()
    for parent in (cwd, *cwd.parents):
        if (parent / ".aah").is_dir():
            return parent
    return None


def main() -> None:
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)

    from aah.core.guards._trace import trace
    from aah.core.guards.delegation_guard import exit_if_delegated
    exit_if_delegated()

    if os.environ.get(BYPASS_ENV) == "1":
        trace("dependency_policy_guard", "bypass")
        sys.exit(0)

    tool_name = hook_input.get("tool_name", "") or ""
    if tool_name != "Bash":
        trace("dependency_policy_guard", "noop", "non-bash")
        sys.exit(0)

    command = (hook_input.get("tool_input", {}) or {}).get("command", "") or ""
    if not command:
        trace("dependency_policy_guard", "noop", "empty-command")
        sys.exit(0)

    # Detect package installs in the command.
    packages = _extract_packages(command)
    if not packages:
        trace("dependency_policy_guard", "noop", "no-install")
        sys.exit(0)

    # Locate the project's policy.
    project_root = _find_project_root()
    if project_root is None:
        trace("dependency_policy_guard", "noop", "no-project-root")
        sys.exit(0)
    policy = _load_policy(project_root)
    if not policy:
        trace("dependency_policy_guard", "noop", "no-policy")
        sys.exit(0)

    # Walk requested packages; check each against the relevant ecosystem's policy.
    violations: list[str] = []
    for ecosystem, spec in packages:
        eco_policy = policy.get(ecosystem) or {}
        if not isinstance(eco_policy, dict) or not eco_policy:
            continue
        name, version = _split_pkg_spec(ecosystem, spec)
        for pattern, pol_version in eco_policy.items():
            if not isinstance(pol_version, str):
                continue
            if not _glob_matches(pattern, name):
                continue
            if _violates_policy(pol_version, version):
                violations.append(
                    f"  {ecosystem}: {name}@{version or '?'} violates policy {pattern} → {pol_version}"
                )

    if not violations:
        trace(
            "dependency_policy_guard",
            "allow",
            ",".join(f"{eco}:{spec}" for eco, spec in packages)[:200],
        )
        sys.exit(0)

    print(
        "⚠ AAH dependency-policy violation — install blocked:",
        file=sys.stderr,
    )
    for v in violations:
        print(v, file=sys.stderr)
    print(
        f"\nThe project's policy at .aah/dependency-policy.json pins these "
        f"versions intentionally. If you need to deviate, update the policy "
        f"file (or set {BYPASS_ENV}=1 for a one-off bypass) and re-run.",
        file=sys.stderr,
    )
    sys.exit(2)


if __name__ == "__main__":
    main()
