#!/usr/bin/env python3
"""PostToolUse(Write|Edit|MultiEdit) guard: BLOCK fixture writes that introduce
un-registered entity names.

Issue #247, Phase 3 L5-B. PartsPulse-iter-2 issues #5 / #9 (mock-data
inconsistency: hardcoded ``"Plant A"`` / ``"Plant B"`` in fixtures
that don't match the canonical entity registry) bypassed every
runtime check because the JSON parses fine and the smoke endpoints
return 200 — the bug only surfaces when business logic that depends
on canonical entity names looks up a non-existent entity.

This guard fires AFTER a Write/Edit/MultiEdit lands a file matching
``**/mock*.json`` / ``**/fixtures*.json`` / ``**/seed*.json`` /
``**/test-data/**.json``. It re-reads the file, walks the JSON for
candidate entity-name strings, and rejects writes that introduce
strings not present (even fuzzy-matched) in
``.aah/entity-registry.json``.

The registry is generated by ``aah.core.plan.build_entity_registry``
during plan-phase from feature YAMLs' optional ``entities:`` blocks
(brownfield: also from existing fixtures). The user can edit the
registry by hand; the generator is idempotent.

Escape hatches:
  - ``AAH_MOCK_DATA_BYPASS=1`` — for legitimate one-off writes.
  - ``delegation_guard.exit_if_delegated()`` for plugin-managed
    projects.

Exit codes:
  0 — write allowed (no registry / not a fixture / all entities canonical)
  2 — write blocked (un-registered entity)

False-positive policy: the fuzzy-match (lowercase substring) is
intentionally generous. A fixture string ``"Plant A"`` matches the
registered canonical ``"plant"`` because the registered name is a
substring (case-insensitive) of the candidate. We bias toward false
negatives (misses) over false positives (legitimate writes blocked) —
the cost of the latter is high (interrupted agent flow), the cost of
the former is contained (downstream business-logic test will catch
it).
"""

from __future__ import annotations

import fnmatch
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

from aah.core.common.io_utils import read_json


BYPASS_ENV = "AAH_MOCK_DATA_BYPASS"


# Path-fragment globs that mark a fixture/mock/seed file. Matched against
# the lowercased posix path. Case-insensitive by design.
_FIXTURE_GLOBS: tuple[str, ...] = (
    "*mock*.json",
    "*fixtures*.json",
    "*seed*.json",
    "*-mocks.json",
    "*-fixtures.json",
)
_FIXTURE_DIR_HINTS: tuple[str, ...] = (
    "/test-data/",
    "/test_data/",
    "/fixtures/",
    "/mocks/",
)


def _is_fixture_file(file_path: str) -> bool:
    if not file_path.lower().endswith(".json"):
        return False
    norm = file_path.replace("\\", "/").lower()
    fname = norm.rsplit("/", 1)[-1]
    if any(fnmatch.fnmatch(fname, glob) for glob in _FIXTURE_GLOBS):
        return True
    if any(hint in norm for hint in _FIXTURE_DIR_HINTS):
        return True
    return False


def _extract_file_path(tool_name: str, tool_input: dict) -> str:
    """Return the target file path for any of Write / Edit / MultiEdit."""
    if tool_name in ("Write", "Edit"):
        return tool_input.get("file_path", "") or ""
    if tool_name == "MultiEdit":
        top = tool_input.get("file_path", "")
        if top:
            return top
        for edit in tool_input.get("edits", []) or []:
            if isinstance(edit, dict):
                fp = edit.get("file_path", "")
                if fp:
                    return fp
    return ""


def _find_project_root(start: Path) -> Path | None:
    """Walk up from ``start`` looking for the nearest ``.aah`` directory."""
    candidates = [start, *start.parents] if start.is_absolute() else [Path.cwd(), *Path.cwd().parents]
    for parent in candidates:
        if (parent / ".aah").is_dir():
            return parent
    return None


def _load_registry(project_path: Path) -> set[str] | None:
    """Load .aah/entity-registry.json. Returns lowercased set or None."""
    reg_path = project_path / ".aah" / "entity-registry.json"
    if not reg_path.exists():
        return None
    try:
        data = read_json(reg_path)
    except Exception:
        return None
    if not isinstance(data, dict):
        return None
    entities = data.get("entities", [])
    if not isinstance(entities, list):
        return None
    return {str(e).lower().strip() for e in entities if e}


# Identifier-shaped strings only. We don't want to flag arbitrary prose
# values like "An item description" — only short tokens that look like
# entity references.
_IDENT_PATTERN = re.compile(r"^[A-Za-z][\w\-]{1,40}$")
_NAMEISH_KEY_PATTERN = re.compile(r"(_id|_name|_type|Type|Name|Id)$")


def _walk_json_for_candidates(node: Any, candidates: list[str], path: str = "") -> None:
    """Recursively walk a parsed-JSON ``node`` collecting candidate
    entity-name strings.

    Heuristic: only collect strings (a) that look like an identifier
    AND (b) appear under a key matching ``_NAMEISH_KEY_PATTERN`` OR
    are short capitalized words.
    """
    if isinstance(node, dict):
        for k, v in node.items():
            new_path = f"{path}.{k}" if path else k
            if isinstance(v, str):
                if _is_candidate(v, parent_key=k):
                    candidates.append(v)
            else:
                _walk_json_for_candidates(v, candidates, new_path)
    elif isinstance(node, list):
        for i, item in enumerate(node):
            new_path = f"{path}[{i}]"
            if isinstance(item, str):
                if _is_candidate(item, parent_key=""):
                    candidates.append(item)
            else:
                _walk_json_for_candidates(item, candidates, new_path)


def _is_candidate(value: str, *, parent_key: str) -> bool:
    """Decide whether `value` looks like an entity reference worth
    checking against the registry."""
    s = value.strip()
    if not s or len(s) > 60:
        return False
    # Strings under name-like keys are always candidates.
    if parent_key and _NAMEISH_KEY_PATTERN.search(parent_key):
        return True
    # Otherwise: only short, identifier-shaped, capitalized strings.
    # ("Plant A" qualifies; "An item description" does not because it
    # contains a space-separated lowercase token at the end.)
    if " " in s:
        # Allow if EVERY space-separated token is capitalized (e.g. "Plant A").
        toks = s.split()
        if all(t[:1].isupper() and t.isascii() for t in toks):
            return True
        return False
    return bool(_IDENT_PATTERN.match(s))


def _matches_registry(candidate: str, registry: set[str]) -> bool:
    """Fuzzy match: registered name is a (lowercased) substring of the
    candidate, OR vice versa. Tolerates "Plant A"/"plant"/"plants"."""
    cl = candidate.lower()
    for reg in registry:
        if not reg:
            continue
        if reg in cl or cl in reg:
            return True
    return False


def main() -> None:
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)

    from aah.core.guards._trace import trace
    from aah.core.guards.delegation_guard import exit_if_delegated
    exit_if_delegated()

    if os.environ.get(BYPASS_ENV) == "1":
        trace("mock_data_consistency_guard", "bypass")
        sys.exit(0)

    tool_name = hook_input.get("tool_name", "") or ""
    tool_input = hook_input.get("tool_input", {}) or {}
    file_path = _extract_file_path(tool_name, tool_input)
    if not file_path or not _is_fixture_file(file_path):
        trace("mock_data_consistency_guard", "noop", file_path or "no-path")
        sys.exit(0)

    target = Path(file_path)
    if not target.exists():
        # PostToolUse fires after the write — if the file is absent,
        # something else (a different guard, a delete) intervened.
        trace("mock_data_consistency_guard", "noop", "file-missing")
        sys.exit(0)

    project_root = _find_project_root(target)
    if project_root is None:
        trace("mock_data_consistency_guard", "noop", "no-project-root")
        sys.exit(0)
    registry = _load_registry(project_root)
    if not registry:
        # No registry → no enforcement; the guard is a no-op until the
        # plan-phase generator seeds it.
        trace("mock_data_consistency_guard", "noop", "no-registry")
        sys.exit(0)

    try:
        data = read_json(target)
    except Exception:
        # Not parseable JSON — out of scope for this guard.
        trace("mock_data_consistency_guard", "noop", "not-parseable")
        sys.exit(0)

    candidates: list[str] = []
    _walk_json_for_candidates(data, candidates)
    # Dedup while preserving order for deterministic stderr.
    seen: set[str] = set()
    unique: list[str] = []
    for c in candidates:
        if c not in seen:
            seen.add(c)
            unique.append(c)

    offenders = [c for c in unique if not _matches_registry(c, registry)]
    if not offenders:
        trace("mock_data_consistency_guard", "allow", file_path)
        sys.exit(0)

    print(
        f"⚠ AAH mock-data consistency violation in {file_path}:",
        file=sys.stderr,
    )
    for o in offenders[:10]:
        print(f"  {o!r} not found in entity registry", file=sys.stderr)
    if len(offenders) > 10:
        print(f"  ... and {len(offenders) - 10} more", file=sys.stderr)
    print(
        f"\nRegistered entities: {sorted(registry)}\n"
        f"Either add the new entity to .aah/entity-registry.json (or rebuild "
        f"via `aah run core.plan.build_entity_registry build`), "
        f"or rename the fixture entity. Set {BYPASS_ENV}=1 to bypass this guard.",
        file=sys.stderr,
    )
    sys.exit(2)


if __name__ == "__main__":
    main()
